import { StyleSheet } from 'react-native';
import { AppColors } from './AppColors';
import { AppTypography } from './AppTypography';
import { GlobalStyles } from './GlobalStyles';

export const TripInfoScreenStyles = StyleSheet.create({
  container: {
    ...GlobalStyles.container,
    backgroundColor: AppColors.backgroundSecondary,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: AppColors.backgroundSecondary,
  },
  headerLeftContainer: {
    flex: 1,
    alignItems: 'flex-start',
  },
  headerRightContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  backButton: {
    fontSize: AppTypography.fontSizeRegular,
    color: AppColors.textHyperlink,
  },
  headerTitle: {
    fontSize: AppTypography.fontSizeLarge,
    fontWeight: AppTypography.fontWeightBold,
    color: AppColors.textPrimary,
    textAlign: 'center',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  section: {
    marginBottom: 24,
  },
  tripTitle: {
    fontSize: AppTypography.fontSizeTitle,
    fontWeight: AppTypography.fontWeightBold,
    color: AppColors.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: AppTypography.fontSizeLarge,
    fontWeight: AppTypography.fontWeightSemiBold,
    color: AppColors.textPrimary,
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  descriptionCard: {
    backgroundColor: AppColors.backgroundCard,
    padding: 16,
    borderRadius: 12,
    shadowColor: AppColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 80,
  },
  descriptionText: {
    flex: 1,
    fontSize: AppTypography.fontSizeMedium,
    color: AppColors.textSecondary,
    lineHeight: 20,
    textAlignVertical: 'top',
  },
  dateRow: {
    flexDirection: 'row',
    gap: 12,
  },
  dateButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: AppColors.borderPrimary,
    borderRadius: 8,
    padding: 12,
    backgroundColor: AppColors.backgroundCard,
  },
  dateButtonText: {
    fontSize: AppTypography.fontSizeMedium,
    color: AppColors.textPrimary,
    textAlign: 'center',
  },
  durationSubtextContainer: {
    marginTop: 8,
    alignItems: 'center',
  },
  durationSubtext: {
    fontSize: AppTypography.fontSizeMedium,
    color: AppColors.textSecondary,
  },
  membersCard: {
    backgroundColor: AppColors.backgroundCard,
    padding: 16,
    borderRadius: 12,
    shadowColor: AppColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  membersCount: {
    fontSize: AppTypography.fontSizeRegular,
    color: AppColors.textPrimary,
    fontWeight: AppTypography.fontWeightMedium,
    marginRight: 12,
  },
  membersList: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  memberName: {
    fontSize: AppTypography.fontSizeMedium,
    color: AppColors.textSecondary,
  },
  chevron: {
    fontSize: AppTypography.fontSizeLarge + 2,
    color: AppColors.textLight,
    marginLeft: 8,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: AppTypography.fontSizeLarge,
    color: AppColors.textSecondary,
  },
  ledgerCard: {
    backgroundColor: AppColors.backgroundCard,
    padding: 16,
    borderRadius: 12,
    shadowColor: AppColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  ledgerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  ledgerLabel: {
    fontSize: AppTypography.fontSizeRegular,
    color: AppColors.textPrimary,
    fontWeight: AppTypography.fontWeightMedium,
  },
  ledgerValue: {
    fontSize: AppTypography.fontSizeRegular,
    color: AppColors.textHyperlink,
    fontWeight: AppTypography.fontWeightSemiBold,
  },
  ledgerSeparator: {
    height: 1,
    backgroundColor: AppColors.borderPrimary,
    marginVertical: 12,
  },
  settlementButtonCompact: {
    backgroundColor: AppColors.primaryBlue,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: AppColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  settlementButtonCompactText: {
    fontSize: AppTypography.fontSizeMedium + 1,
    fontWeight: AppTypography.fontWeightSemiBold,
    color: AppColors.textPrimary,
    letterSpacing: 0.2,
  },
  manageTripButtonText: {
    fontSize: AppTypography.fontSizeRegular,
    color: AppColors.textHyperlink,
    fontWeight: AppTypography.fontWeightSemiBold,
  },
  manageTripButtons: {
    marginTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 0,
    gap: 10,
  },
  primaryActionButton: {
    backgroundColor: AppColors.primaryBlue,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 0,
    shadowColor: AppColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  primaryActionButtonText: {
    fontSize: AppTypography.fontSizeMedium + 1,
    fontWeight: AppTypography.fontWeightSemiBold,
    color: AppColors.textPrimary,
    letterSpacing: 0.2,
  },
  successActionButton: {
    backgroundColor: '#34C759',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 0,
    shadowColor: AppColors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  successActionButtonText: {
    fontSize: AppTypography.fontSizeMedium + 1,
    fontWeight: AppTypography.fontWeightSemiBold,
    color: AppColors.textPrimary,
    letterSpacing: 0.2,
  },
  destructiveActionButton: {
    backgroundColor: 'rgba(255, 69, 58, 0.1)',
    borderWidth: 1,
    borderColor: AppColors.redError,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 0,
  },
  destructiveActionButtonText: {
    fontSize: AppTypography.fontSizeMedium + 1,
    fontWeight: AppTypography.fontWeightSemiBold,
    color: AppColors.redError,
    letterSpacing: 0.2,
  },
  datePickerOverlay: GlobalStyles.datePickerOverlay,
  datePickerContainer: GlobalStyles.datePickerContainer,
  datePickerHeader: GlobalStyles.datePickerHeader,
  datePickerCancel: GlobalStyles.datePickerCancel,
  datePickerTitle: GlobalStyles.datePickerTitle,
  datePickerDone: GlobalStyles.datePickerDone,
  pickerRow: GlobalStyles.pickerRow,
  picker: GlobalStyles.picker,
});